### ISSUE TITLE
cpp: include DataStream must always use the "utils" namespace

### ISSUE THREAD

**Issue by plata** [open-dis/xmlpg#14]
Currently, the namespace defined in the xml is used.

**Comment by mcgredonps** [comment]
Yes, I wrote two separate XML for DIS 6 and 7. There are some inevitable errors going on. Unless there's a more modern C++ you can configure the configure it with the xml is used.

**Comment by plata** [comment]
Sorry, I don't quite understand your comment. Is there any particular reason not to simply write `#include <utils/DataStream.h>` in `CppGenerator`?

**Comment by leif81** [comment]
This was fixed in #25
