### ISSUE TITLE
Fix DIS2012.xml

### ISSUE THREAD

**Issue by plata** [open-dis/xmlpg#9]
The XML format does not match the one used by xmlpg. Also, the file should be linted.

**Comment by leif81** [comment]
Thanks @plata 

There were some changes on 25 Aug 2018 to the file that may have addressed your issues. 

https://github.com/open-dis/xmlpg/commits/master/DIS2012.xml

I'm not seeing an issue when I run xmlpg with dis2012.xml with java or cpp.

If you still see an issue can you please reopen this.
